### ISSUE TITLE
pysmurf writing >16 bit number for etaMag 

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#24]
Today, while running dspv3 branch with R1.3.1 pyrogue docker, got a lot of this error:

```
ERROR:pyrogue.RemoteVariable.etaMag[316]:"Memory Error for etaMag[316] at address 0x812104f0  Invalid value '162099' for base type <class 'int'> with bit size 16"
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/pyrogue/_Variable.py", line 184, in set
   self._block.set(self, value)
 File "/usr/local/lib/python3.6/dist-packages/pyrogue/_Block.py", line 372, in set
   raise MemoryError(name=var.name, address=self.address, msg=msg)
pyrogue._Block.MemoryError: "Memory Error for etaMag[316] at address 0x812104f0  Invalid value '162099' for base type <class 'int'> with bit size 16"
ERROR:pyrogue.RemoteVariable.etaMag[316]:Error setting value '162099' to variable 'AMCc.FpgaTopLevel.AppTop.AppCore.SysgenCryo.Base[2].CryoChannels.etaMag[316]' with type UInt16
ERROR:pyrogue.RemoteVariable.etaMag[280]:"Memory Error for etaMag[280] at address 0x81210460  Invalid value '88069' for base type <class 'int'> with bit size 16"
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/pyrogue/_Variable.py", line 184, in set
   self._block.set(self, value)
 File "/usr/local/lib/python3.6/dist-packages/pyrogue/_Block.py", line 372, in set
   raise MemoryError(name=var.name, address=self.address, msg=msg)
```
Looks like somewhere we're writing the wrong format numbers to etaMag.

**Comment by ruck314** [comment]
I believe this has been resolved on `main` and can likely be closed.

**Root cause.** The firmware `etaMag[k]` register is UInt16 and stores a *scaled* quantity, `eta_scaled = eta_mag / subband_half_width`, with the representable range `eta_scaled ∈ [0, 1]`. When `eta_fit` / `setup_notches` produced `eta_scaled > 1`, the encoded integer exceeded `0xFFFF` and rogue's per-element `to_bytes(...)` raised the `bit size 16` `MemoryError` shown in the report. The example values map cleanly to fractional overshoot:

- `162099 / 65535 ≈ 2.47` → `eta_scaled ≈ 2.47` for `etaMag[316]`
- `88069  / 65535 ≈ 1.34` → `eta_scaled ≈ 1.34` for `etaMag[280]`

(Same underlying problem as #620, where the symptom was `etaI[k]` / `etaQ[k]` overflow rather than `etaMag[k]` directly.)

**Fix already on main.** Commit [`d96c05d5`](https://github.com/slaclab/pysmurf/commit/d96c05d5) — *fix(smurf_tune): Ensure eta_scaled <= 1* — clamps `eta_scaled` to 1 (and rescales `eta_mag` back to `subband_half_width`) at all three sites that compute eta before writing it to firmware:

- `python/pysmurf/client/tune/smurf_tune.py:1321` — `eta_fit`
- `python/pysmurf/client/tune/smurf_tune.py:4006` — `setup_notches`, assigned-channel path
- `python/pysmurf/client/tune/smurf_tune.py:4066` — `setup_notches`, unassigned-channel path

A `self.log(...)` is emitted whenever clipping occurs, so over-range eta measurements still surface in the pysmurf log even though they no longer overflow the firmware register.

**Recommendation.** Once a build containing `d96c05d5` is deployed, the `MemoryError ... bit size 16` traffic on `etaMag[k]` should disappear. I'd suggest closing this issue and reopening only if the error is observed again on a build that includes that commit.
