### ISSUE TITLE
Estimate Phase Delay return values can exceed limits set by schema

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#619]
## Describe the bug
When running estimate_phase_delay on smurf-srv20, we're getting large values for  refPhaseDelayFine:
```
-------------------------------------------------------
Estimated refPhaseDelay=24
Estimated refPhaseDelayFine=2324
Estimated processing_delay_us=9.004375214891974
-------------------------------------------------------
 ```
However when we try to set this in in the pysmurf config file, we get the following schema errors:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/schema.py", line 431, in validate
    return s.validate(data)
  File "/usr/local/lib/python3.6/dist-packages/schema.py", line 128, in validate
    data = s.validate(data)
  File "/usr/local/lib/python3.6/dist-packages/schema.py", line 451, in validate
    raise SchemaError(message, e)
schema.SchemaError: <lambda>(2324) should evaluate to True
```
Looking through the code it seems as though refPhaseDelayFine > 2**8 is invalid in the config file, so seems like either estimate_phase_delay is returning invalid params or the schema is off.

## Expected behavior
We should be able to load values returned by estimate_phase_delay in the pysmurf config file.

**Comment by aer7** [comment]
Might be compatibility issue, haven't seen it in a while.

**Comment by aer7** [comment]
NO I SEE IT

**Comment by aer7** [comment]
[mozilla.pdf](https://github.com/slaclab/pysmurf/files/8694087/mozilla.pdf)

**Comment by aer7** [comment]
Yeah, something with v4.3.0 is unhappy. Check out the post-correction on estimate_phase_delay.
![Screen Shot 2022-05-14 at 5 40 55 PM](https://user-images.githubusercontent.com/89935000/168452634-c9fb5db3-840f-43db-a28f-dc1a553c93ec.png)

**Comment by aer7** [comment]
Not sure if related, #469. Switching from v4.3.0 SW to v6.0.0 SW fixes the issue, keeping v4.3.0 FW. What fixes it?

**Comment by aer7** [comment]
![Screen Shot 2022-05-14 at 7 06 35 PM](https://user-images.githubusercontent.com/89935000/168454178-01a31f55-0516-442e-815c-94272de97e02.png)

**Comment by ruck314** [comment]
The original failure mode — `estimate_phase_delay` producing values that overflow the 8-bit `refPhaseDelayFine` schema validator — has been resolved on `main` since April 2021 by these two commits:

- c373a69 — `estimate_phase_delay` now uses `set_band_delay_us(...)` internally and returns `dsp_delay_us` / `dsp_corr_delay_us` (microseconds). The firmware/Rogue layer is responsible for splitting that into the underlying coarse/fine register fields, so the Python config never sees the raw 8-bit value.
- 28908f6 — Added `bandDelayUs` (range `0 <= n < 30` µs) to the config schema and marked `refPhaseDelay` / `refPhaseDelayFine` as `Optional` and deprecated.

The estimator's reported `dsp_delay_us` (≈9 µs in the original report) maps cleanly onto `bandDelayUs` and is well within the schema range. This also matches @agustiner's 2022-05-15 follow-up that the issue does not reproduce on v5.x / v6.0.0.

Recommend closing as fixed.
