### ISSUE TITLE
Epics OverflowError

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#620]
## Describe the bug
Rogue logs are full of error messages like this:
```
1615342538.361129:pyrogue.epicsV3.Value: Error setting value from epics: smurf_server_s3:AMCc:FpgaTopLevel:AppTop:AppCore:SysgenCryo:Base[1]:CryoChannels:etaMagArray
ERROR:pyrogue.Variable.RemoteVariable.AMCc.FpgaTopLevel.AppTop.AppCore.SysgenCryo.Base[2].CryoChannels.etaQ[4]:int too big to convert
Traceback (most recent call last):
  File "/usr/local/src/rogue/python/pyrogue/_Variable.py", line 324, in set
    self._block.set(self, value)
  File "/usr/local/src/rogue/python/pyrogue/_Block.py", line 362, in set
    ba = var._base.toBytes(value)
  File "/usr/local/src/rogue/python/pyrogue/_Model.py", line 128, in toBytes
    ba = value.to_bytes(byteCount(self.bitSize), self.endianness, signed=True)
OverflowError: int too big to convert
```

## Additional details
Doesn't crash or stop us from taking data so I don't think it's urgent, but it does fill up logs and seems like a relatively easy fix to clamp the eta vars or something before setting.

**Comment by aer7** [comment]
Yeah not sure where this issue is coming from. Maybe some function calls set_eta_mag_array with some invalid eta_mag parameter? Wontfix for now.

**Comment by ruck314** [comment]
I believe this has been resolved on `main` and can likely be closed.

**Root cause.** The `OverflowError: int too big to convert` in the traceback originates from rogue's `_Model.toBytes`:

```
File "/usr/local/src/rogue/python/pyrogue/_Model.py", line 128, in toBytes
    ba = value.to_bytes(byteCount(self.bitSize), self.endianness, signed=True)
```

`etaQ[k]` / `etaI[k]` are the firmware's signed fixed-point quadrature components of `etaMag * exp(j*etaPhase)`. The register's representable range corresponds to a scaled magnitude `<= 1` (i.e. `eta_mag <= subband_half_width`). When `eta_fit` / `setup_notches` measured an `eta_scaled > 1` and the resulting array was pushed via `set_eta_mag_array` / `set_eta_phase_array`, rogue's per-element `to_bytes(...)` of the derived `etaI`/`etaQ` integers overflowed for the offending channels, producing exactly this log spam.

**Fix already on main.** Commit [`d96c05d5`](https://github.com/slaclab/pysmurf/commit/d96c05d5) — *fix(smurf_tune): Ensure eta_scaled <= 1* — clamps `eta_scaled` to 1 (and rescales `eta_mag` back to `subband_half_width`) at all three sites that compute eta before writing it to firmware:

- `python/pysmurf/client/tune/smurf_tune.py:1321` — `eta_fit`
- `python/pysmurf/client/tune/smurf_tune.py:4006` — `setup_notches`, assigned-channel path
- `python/pysmurf/client/tune/smurf_tune.py:4066` — `setup_notches`, unassigned-channel path

A `self.log(...)` is emitted whenever clipping occurs, so over-range eta measurements still surface in the pysmurf log even though they no longer overflow the firmware register.

**Recommendation.** Once a build containing `d96c05d5` is deployed, the rogue EPICS `OverflowError` traffic from `etaI[k]` / `etaQ[k]` should disappear. I'd suggest closing this issue and reopening only if the error is observed again on a build that includes that commit.
