### ISSUE TITLE
SerialGradientDescent failures

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#722]
## Describe the bug
I'm playing around with tuning serial gradient descent, and fairly often it seems to fail with this error:
```
ERROR:pyrogue.Device.SerialGradientDescent.AMCc.FpgaTopLevel.AppTop.AppCore.SysgenCryo.Base[0].CryoChannels.SerialGradientDescent:int too big to convert
Traceback (most recent call last):
  File "/usr/local/src/rogue/python/pyrogue/_Process.py", line 100, in _run
    self._process()
  File "/tmp/fw/rogue_MicrowaveMuxBpEthGen2_v1.1.0.zip/python/CryoDet/DspCoreLib/CryoDetCmbHcd/_SerialGradientDescent.py", line 97, in _process
    dx     = calcGrad( centerFreqVar, freqErrorVar, etaPhaseVar, freq[channel] + currDf, initialStep, numAverages ) # center difference
  File "/tmp/fw/rogue_MicrowaveMuxBpEthGen2_v1.1.0.zip/python/CryoDet/DspCoreLib/CryoDetCmbHcd/_SerialGradientDescent.py", line 28, in calcGrad
    centerFreqVar.set( centerFrequencyMHz + df )
  File "/usr/local/src/rogue/python/pyrogue/_Variable.py", line 839, in set
    varFuncHelper(self._linkedSet,pargs,self._log,self.path)
  File "/usr/local/src/rogue/python/pyrogue/_Variable.py", line 868, in varFuncHelper
    return func(**args)
  File "/tmp/fw/rogue_MicrowaveMuxBpEthGen2_v1.1.0.zip/python/CryoDet/DspCoreLib/CryoDetCmbHcd/_CryoChannel.py", line 94, in <lambda>
    linkedSet    = lambda var, value, write: var.dependencies[0].set(int(round((value*2**23./freqSpanMHz))), write=write),
  File "/usr/local/src/rogue/python/pyrogue/_Variable.py", line 334, in set
    raise e
  File "/usr/local/src/rogue/python/pyrogue/_Variable.py", line 324, in set
    self._block.set(self, value)
  File "/usr/local/src/rogue/python/pyrogue/_Block.py", line 362, in set
    ba = var._base.toBytes(value)
  File "/usr/local/src/rogue/python/pyrogue/_Model.py", line 128, in toBytes
    ba = value.to_bytes(byteCount(self.bitSize), self.endianness, signed=True)
OverflowError: int too big to convert
```

This seems like it's probably due to parameters causing the lms operation to runaway which is reasonable, however it only shows up in the rogue output, and that is saturated with warnings like this so it is very easy to miss. Also this isn't handled at all in the serialGradientDescent command, so it leaves the system in a bad state with the amplitude-scale-arrays zeroed out, and the `etaScanInProgress` variable left at 1, so it won't run anymore eta scan operations.

**Comment by ruck314** [comment]
Hi @jlashner — revisiting this for cleanup. I believe this can be closed once #893 lands, for two reasons:

**1. The original firmware overflow has been removed.** cryo-det [PR #60](https://github.com/slaclab/cryo-det/pull/60) (commit [`175e67c`](https://github.com/slaclab/cryo-det/commit/175e67c86baa4a5b2b7ceb8b25ea08d0161d3450), merged 2026-03-20) replaced `SerialGradientDescent` with a Barzilai–Borwein method. The runaway-prone update you saw (`v = beta*v + (1-beta)*gain*dx; currDf -= v`) is gone — the new algorithm uses self-scaling step sizes (`alpha = |df/dg|`) with no cross-iteration accumulator, plus an explicit out-of-range guard. `gradientDescentBeta` / `gradientDescentMomentum` / `gradientDescentGain` are now no-ops with deprecation listeners. Pysmurf [PR #889](https://github.com/slaclab/pysmurf/pull/889) is in flight to remove the matching deprecated config knobs.

**2. Pysmurf no longer leaves the band stuck on a firmware-side abort.** Your second concern — `etaScanInProgress` left at `1` after a firmware exception, blocking every subsequent eta scan — is addressed by [PR #893](https://github.com/slaclab/pysmurf/pull/893). `run_serial_gradient_descent`, `run_serial_eta_scan`, and `run_serial_min_search` now wrap `_wait_for()` so that on `TimeoutError` they log a clear ERROR pointing at the rogue logs, force-clear `etaScanInProgress` back to `0`, and re-raise. A new `set_eta_scan_in_progress()` recovery setter is also added.

One caveat that I left out of #893 (worth surfacing): the firmware `_process` still zeroes the per-channel `amplitudeScale` array at the start and only restores it at the end, so on abort it is left zeroed. Restoring it from pysmurf would require reading it before triggering and changes the success path too — happy to take that as a follow-up if it's been hurting you in practice; otherwise I'd lean on the new BB algorithm being substantially less abort-prone.

Recommend closing once #893 merges. Let me know if you've seen this fail on current firmware and I'll re-open.
